#!/usr/bin/env python

import os
import os.path as op
import shutil

# os.walk, os.symlink, os.listdir
# shutil.copytree
# op.realpath, op.islink, op.samefile

def find_files():
    result = []
    for root, dirs, files in os.walk('files'):
        result.extend([op.join(root, filename) for filename in files])
    result = [op.relpath(pathname, 'files') for pathname in result]
    return result

def add_dots():
    return ['.' + fn for fn in find_files()]

def create_symlinks():
    real_first_level_paths = add_dots()
