#!/bin/zsh
# This hook is run after every virtualenv is activated.
#
export VIRTUALENVWRAPPER_PROJECT_DIR=$(cat $VIRTUAL_ENV/$VIRTUALENVWRAPPER_PROJECT_FILENAME)
export VIRTUALENVWRAPPER_PROJECT_NAME=${VIRTUAL_ENV:t}
