#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"
export PYTHONDOCS="/usr/share/doc/python/html"
export PAGER="less -R"

if [[ $HOSTNAME == "caballo" ]]; then
    export EDITOR="vim"
    mkdir -p "$XDG_RUNTIME_DIR/urxvt"
    export RXVT_SOCKET="${XDG_RUNTIME_DIR}/urxvt/urxvtd-${HOST}"

    # For Python
    # Enables me to import modeller modules
    MODELLER_PATH="/usr/lib/modeller"
    export PYTHONPATH="$MODELLER_PATH/modlib:$MODELLER_PATH/lib/x86_64-intel8/python2.5"
    export PYTHON3PATH="$MODELLER_PATH/modlib:$MODELLER_PATH/lib/x86_64-intel8/python3.2"

    # For virtualenv
    export VIRTUAL_ENV_DISABLE_PROMPT=1
    export WORKON_HOME="${XDG_DATA_HOME}/virtualenv/envs"
    export PROJECT_HOME="${HOME}/prj"
    export VIRTUALENVWRAPPER_HOOK_DIR="${XDG_DATA_HOME}/virtualenv/hooks"
    export VIRTUALENVWRAPPER_LOG_DIR="${HOME}/.log/virtualenv"
    export VIRTUALENVWRAPPER_VIRTUALENV_ARGS="--no-site-packages --distribute"
    # make pip automatically use a virtualenv if it's active
    export PIP_VIRTUALENV_BASE=${WORKON_HOME}
    export PIP_RESPECT_VIRTUALENV=true

    # for notmuch mail index program
    export NOTMUCH_CONFIG="${XDG_CONFIG_HOME}/notmuch/notmuch.conf"
elif [[ $HOSTNAME == "molmod19" ]]; then
    export PATH="$HOME/.local/epd/7.3.1/bin:$PATH"
    export EDITOR="gvim"

    MODELLER_PATH="$HOME/.local/modeller/9.10"
    export PYTHONPATH="$MODELLER_PATH/modlib:$MODELLER_PATH/lib/i386-intel8/python2.5"
fi
