#!/bin/bash

# See if external screen is connected
if [[ $(xrandr | grep "HDMI1 connected") ]]; then
    xrandr --output HDMI1 --auto --output LVDS1 --auto --primary --below HDMI1
fi

# Set X properties
xrdb -merge ~/.Xresources

# Set background
imlibsetroot -x 0 -s -p c ~/.config/background.jpg -x 1 -s -p c ~/.config/background.jpg  

# Set cursor
xsetroot -cursor_name left_ptr

# Set color temperature depending on time of day
redshift &

# Set GTK2 RC file location
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# Start WM/DE
exec i3
