#!/bin/bash

sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources="$HOME/.Xresources"
usermodmap="$HOME/.Xmodmap"

# Merge in defaults and keymaps
[ -f $sysresources ] && xrdb -merge "$sysresources"
[ -f $sysmodmap ] && xmodmap "$sysmodmap"
[ -f $userresources ] && xrdb -merge "$userresources"
[ -f $usermodmap ] && xmodmap "$usermodmap"

# Start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && source "$f"
  done
fi

source "$HOME/.xprofile"

# Start WM/DE
exec awesome
