#!/bin/sh

source $HOME/.profile

# Appearance {{{
# Need this in order to use GTK style for Qt
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

# }}}
# XBK Settings {{{
XKBDIR="${XDG_DATA_HOME:-$HOME/.local/share}/X11/xkb"
XKBKEYMAPFILE="$XKBDIR/keymaps/default.xkb"
xkbcomp -I$XKBDIR $XKBKEYMAPFILE $DISPLAY

# }}}
# vim: foldmethod=marker
